INSERT INTO item (nome, tipo) VALUES
('Joia', 'J'),
('Hackett-Stamm', 'A'),
('Tillman-Konopelski', 'A'),
('Kirlin-Bogan', 'A'),
('Block-Tillman', 'A'),
('Hegmann-Steuber', 'A'),
('Gerhold-McLaughlin', 'A'),
('Grimes-Ebert', 'A'),
('Kuhlman-Rosenbaum', 'A'),
('Cole-Wilderman', 'A'),
('Zemlak-Quigley', 'A'),
('Macejkovic-Okuneva', 'A'),
('Botsford-Kozey', 'A'),
('Kris-Douglas', 'A'),
('Brekke-Konopelski', 'A'),
('Wolf-Daniel', 'A'),
('Runolfsson-Roberts', 'A'),
('Roob-Mayert', 'A'),
('Kuhic-Cole', 'A'),
('Rowe-Padberg', 'A');

INSERT INTO trocavel (nome, tipo) VALUES
('Zulauf-McCullough', 'A'),
('Hackett-Stamm', 'A'),
('Tillman-Konopelski', 'A'),
('Kirlin-Bogan', 'A'),
('Block-Tillman', 'A'),
('Hegmann-Steuber', 'A'),
('Gerhold-McLaughlin', 'A'),
('Grimes-Ebert', 'A'),
('Kuhlman-Rosenbaum', 'A'),
('Cole-Wilderman', 'A'),
('Zemlak-Quigley', 'A'),
('Macejkovic-Okuneva', 'A'),
('Botsford-Kozey', 'A'),
('Kris-Douglas', 'A'),
('Brekke-Konopelski', 'A'),
('Wolf-Daniel', 'A'),
('Runolfsson-Roberts', 'A'),
('Roob-Mayert', 'A'),
('Kuhic-Cole', 'A'),
('Rowe-Padberg', 'A');

INSERT INTO equipamento (nome, tipo) VALUES
('Zulauf-McCullough', 'A'),
('Hackett-Stamm', 'A'),
('Tillman-Konopelski', 'A'),
('Kirlin-Bogan', 'A'),
('Block-Tillman', 'A'),
('Hegmann-Steuber', 'A'),
('Gerhold-McLaughlin', 'A'),
('Grimes-Ebert', 'A'),
('Kuhlman-Rosenbaum', 'A'),
('Cole-Wilderman', 'A'),
('Zemlak-Quigley', 'A'),
('Macejkovic-Okuneva', 'A'),
('Botsford-Kozey', 'A'),
('Kris-Douglas', 'A'),
('Brekke-Konopelski', 'A'),
('Wolf-Daniel', 'A'),
('Runolfsson-Roberts', 'A'),
('Roob-Mayert', 'A'),
('Kuhic-Cole', 'A'),
('Rowe-Padberg', 'A');


INSERT INTO arma (nome, descricao, quantidade_maxima, valor, nivel_minimo, dano_maximo, dano_critico, rolagens) VALUES
('Stormbreaker', 'Forjado pelos poderes de um deus e a energia uma estrela combinados, na forja de um anão gigante em Nidavellir.', 11, 30, 86, 57, 81, 12),
('Mjolnir', '"Quem quer que possua este martelo, se ele for digno, possuirá o poder de Thor. - Encanto de Mjolnir"', 5, 48, 49, 11, 88, 12),
('Arco e flecha', 'Gavião arqueiro' 41, 11, 74, 55, 92, 5),
('Escudo do capitão américa', 'Um presente do pai do Tony Stark, este escudo consegue resistir a poderes de qualquer natureza e qualquer magnitude.', 17, 81, 42, 98, 25, 14),
('Armadura MK75', 'A última versão da armadura do Homem de Ferro.', 43, 28, 35, 96, 23, 10);