INSERT INTO efeito_vilao (vilao, efeito) VALUES 
('Thanos', 'Super-força'),
('Thanos', 'Super-inteligência'),
('Thanos', 'Pele inquebrável'),
('Fauce de Ébano', 'Super-inteligência'),
('Fauce de Ébano', 'Levitação e manipulação'),
('Corvus Glaive', 'Super-força'),
('Corvus Glaive', 'Super-velocidade'),
('Corvus Glaive', 'Super-resistência'),
('Próxima Meia-Noite', 'Super-força'),
('Próxima Meia-Noite', 'Super-velocidade'),
('Próxima Meia-Noite', 'Super-resistência'),
('Estrela Negra', 'Super-força'),
('Estrela Negra', 'Super-densidade'),
('Estrela Negra', 'Pele inquebrável'),
('Supergigante', 'Telepatia'),
