INSERT INTO estoque (base, item, quantidade) VALUES 
(1, 'Ouro', 34),
(1, 'Prata', 474),
(1, 'Porcao de HP', 99),
(1, 'Porcao de MP', 73),
(1, 'Armadura Simples', 1),
(1, 'Luvas Simples', 1),
(1, 'Botas Simples', 1),
(2, 'Porcao de HP', 5),
(2, 'Porcao de MP', 25),
(2, 'Armadura Simples', 1),
(2, 'Botas Simples', 1),
(3, 'Porcao de HP', 262),
(3, 'Porcao de MP', 256),
(3, 'Ouro', 53456),
(3, 'Capa do morcego', 1),
(3, 'Anel de salto', 1),
(3, 'Chapéu de disfarce', 1),
(3, 'Óculos de noite', 1);
