INSERT INTO consumo (heroi, consumivel, vezes) VALUES
('Helena 3', 'Poção média de magia', 5),
('Herick 3', 'Poção gigante de agilidade', 3),
('Carlos 1', 'Poção média de cura', 5),
('Julio 4', 'Poção pequena de cura', 4),
('Herick 4', 'Poção média de magia', 4),
('Pedro 3', 'Poção de invisibilidade', 4),
('Helena 2', 'Poção de invisibilidade', 1),
('Helena 4', 'Poção pequena de agilidade', 3),
('Helena 4', 'Poção grande de cura', 5),
('Pedro 3', 'Poção gigante de magia', 3),
('Carlos 3', 'Poção pequena de magia', 4),
('Herick 4', 'Poção pequena de magia', 2),
('Julio 2', 'Poção pequena de agilidade', 2),
('Carlos 2', 'Poção pequena de agilidade', 4),
('Herick 3', 'Poção de invisibilidade', 5),
('Herick 1', 'Poção grande de cura', 3),
('Carlos 2', 'Poção grande de cura', 1),
('Pedro 4', 'Poção gigante de cura', 1),
('Herick 1', 'Poção pequena de agilidade', 5),
('Julio 1', 'Poção grande de cura', 5);