INSERT INTO efeito_vilao (vilao, efeito) VALUES 
('Thanos', 'Ataque'),
('Thanos', 'Magia'),
('Thanos', 'Defesa'),
('Fauce de Ébano', 'Magia'),
('Corvus Glaive', 'Ataque'),
('Corvus Glaive', 'Agilidade'),
('Corvus Glaive', 'Defesa'),
('Próxima Meia-Noite', 'Ataque'),
('Próxima Meia-Noite', 'Agilidade'),
('Próxima Meia-Noite', 'Defesa'),
('Estrela Negra', 'Ataque'),
('Estrela Negra', 'Magia'),
('Estrela Negra', 'Defesa'),
('Supergigante', 'Magia');
