INSERT INTO estoque (base, item, quantidade) VALUES 
(3, 'Poção pequena de cura', 12),
(9, 'Poção média de cura', 18),
(2, 'Poção grande de cura', 1),
(6, 'Poção gigante de cura', 18),
(19, 'Poção pequena de agilidade', 11),
(3, 'Poção média de agilidade', 17),
(7, 'Poção grande de agilidade', 16),
(14, 'Poção gigante de agilidade', 19),
(13, 'Poção pequena de magia', 20),
(16, 'Poção média de magia', 15),
(9, 'Poção média de magia', 13),
(16, 'Poção grande de magia', 6),
(13, 'Poção gigante de magia', 14),
(10, 'Poção gigante de magia', 14),
(5, 'Poção gigante de magia', 16),
(9, 'Poção de invisibilidade', 16),
(3, 'Poção de invisibilidade', 2),
(13, 'Poção de invisibilidade', 13),
(5, 'Poção de invisibilidade', 3);
