INSERT INTO luta (heroi, vilao, resultado) VALUES
('Carlos 3', 'Chitauris', 'V'),
('Helena 2', 'Chitauris', 'D'),
('Pedro 1', 'Outriders', 'V'),
('Carlos 3', 'Chitauris', 'V'),
('Julio 4', 'Outriders', 'V'),
('Julio 4', 'Chitauris', 'D'),
('Helena 4', 'Estrela Negra', 'D'),
('Carlos 3', 'Thanos', 'D'),
('Helena 4', 'Próxima Meia-Noite', 'V'),
('Pedro 1', 'Thanos', 'D'),
('Julio 2', 'Fauce de Ébano', 'V'),
('Carlos 4', 'Corvus Glaive', 'D'),
('Julio 3', 'Fauce de Ébano', 'V'),
('Helena 1', 'Corvus Glaive', 'D'),
('Julio 3', 'Chitauris', 'D'),
('Julio 2', 'Sakaarans', 'V'),
('Julio 3', 'Corvus Glaive', 'D'),
('Julio 1', 'Próxima Meia-Noite', 'V'),
('Julio 3', 'Outriders', 'D'),
('Helena 4', 'Chitauris', 'V');