INSERT INTO posse (item, heroi) VALUES
('Manopla MK75', 'Herick 4'),
('Mjölnir', 'Herick 1'),
('Olho de Agamotto', 'Pedro 4'),
('Lança Teias Comum', 'Herick 4'),
('Stormbreaker', 'Helena 2'),
('Stormbreaker', 'Pedro 3'),
('Escudo de Vibranium', 'Pedro 1'),
('Manopla MK75', 'Pedro 2'),
('Mjölnir', 'Carlos 1'),
('Mjölnir', 'Carlos 1'),
('Stormbreaker', 'Pedro 1'),
('Mjölnir', 'Julio 4'),
('Stormbreaker', 'Herick 1'),
('Manopla MK75', 'Helena 1'),
('Lança Teias Comum', 'Herick 4'),
('Lança Teias Comum', 'Helena 4'),
('Escudo de Vibranium', 'Julio 1'),
('Stormbreaker', 'Carlos 1'),
('Manopla MK75', 'Julio 4'),
('Arco e Flecha', 'Herick 2');