INSERT INTO troca (item, heroi, base, quantidade_item, venda_ou_compra) VALUES
('Poção gigante de cura', 'Carlos 4', 17, 8, 'V'),
('Poção grande de cura', 'Pedro 3', 1, 9, 'C'),
('Poção pequena de magia', 'Helena 1', 4, 5, 'C'),
('Poção grande de cura', 'Herick 1', 5, 4, 'V'),
('Poção de invisibilidade', 'Carlos 3', 17, 5, 'V'),
('Poção média de magia', 'Carlos 4', 5, 6, 'C'),
('Poção gigante de agilidade', 'Herick 3', 7, 1, 'V'),
('Poção gigante de magia', 'Julio 2', 18, 5, 'C'),
('Poção gigante de agilidade', 'Herick 3', 13, 5, 'V'),
('Poção pequena de cura', 'Pedro 3', 1, 4, 'C'),
('Poção média de cura', 'Pedro 3', 9, 5, 'C'),
('Poção grande de cura', 'Herick 4', 10, 8, 'C'),
('Poção de invisibilidade', 'Carlos 2', 1, 6, 'C'),
('Poção pequena de magia', 'Herick 4', 15, 1, 'C'),
('Poção média de magia', 'Julio 2', 19, 3, 'V'),
('Poção grande de agilidade', 'Carlos 2', 11, 3, 'C'),
('Poção grande de magia', 'Carlos 4', 12, 6, 'C'),
('Poção pequena de agilidade', 'Pedro 3', 4, 8, 'V'),
('Poção pequena de cura', 'Pedro 2', 17, 9, 'V'),
('Poção grande de magia', 'Herick 3', 3, 4, 'C');