\i dml/arma.sql
\i dml/traje.sql
\i dml/heroi.sql
\i dml/acesso_equipamento.sql
\i dml/joia.sql
\i dml/mapa.sql
\i dml/base.sql
\i dml/efeito.sql
\i dml/consumivel.sql
\i dml/instancia_heroi.sql
\i dml/consumo.sql
\i dml/efeito_arma.sql
\i dml/vilao.sql
\i dml/efeito_vilao.sql
\i dml/espaco_vazio.sql
\i dml/estoque.sql
\i dml/imunidade_traje.sql
\i dml/imunidade_vilao.sql
\i dml/instancia_item.sql
\i dml/instancia_vilao.sql
\i dml/luta.sql
\i dml/moeda.sql
\i dml/posse.sql
\i dml/rastro.sql
\i dml/recompensa.sql
\i dml/troca.sql
\i dml/viagem.sql
